# -*- coding: utf-8 -*-
"""TUGAS PIK.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IecYZJV_QXH0MJz8oMR9760qxMwj7JAE
"""

import json
import os
import random
from datetime import datetime
from typing import List, Dict, Any

# Untuk menampilkan grafik
import matplotlib.pyplot as plt

# File default
SOAL_FILE = "soal.json"
SKOR_FILE = "skor.json"

# ---------------------------
# Utilities: load & save
# ---------------------------
def load_json_file(path: str, default):
    if not os.path.exists(path):
        with open(path, "w", encoding="utf-8") as f:
            json.dump(default, f, indent=2, ensure_ascii=False)
        return default
    with open(path, "r", encoding="utf-8") as f:
        try:
            return json.load(f)
        except json.JSONDecodeError:
            # jika korup/ kosong, reset ke default
            return default

def save_json_file(path: str, data):
    with open(path, "w", encoding="utf-8") as f:
        json.dump(data, f, indent=2, ensure_ascii=False)

# ---------------------------
# Inisialisasi file bila belum ada
# ---------------------------
DEFAULT_SOAL = [
    {
        "pertanyaan": "1. Ibu kota Indonesia adalah?",
        "pilihan": ["Jakarta", "Bandung", "Surabaya", "Medan", "Depok"],
        "jawaban_index": 0
    },
    {
        "pertanyaan": "2. Benua terbesar di dunia adalah?",
        "pilihan": ["Afrika", "Antartika", "Asia", "Eropa", "Australia"],
        "jawaban_index": 2
    },
    {
        "pertanyaan": "3. Planet yang dijuluki sebagai Planet Merah adalah?",
        "pilihan": ["Bumi", "Mars", "Jupiter", "Venus", "Saturnus"],
        "jawaban_index": 1
    },
    {
        "pertanyaan": "4. Lambang kimia dari air adalah?",
        "pilihan": ["CO2", "H2O", "O2", "N2", "H2"],
        "jawaban_index": 1
    },
    {
        "pertanyaan": "5. Hewan tercepat di darat adalah?",
        "pilihan": ["Singa", "Serigala", "Cheetah", "Harimau", "Zebra"],
        "jawaban_index": 2
    },
    {
        "pertanyaan": "6. Mata uang Jepang adalah?",
        "pilihan": ["Won", "Yuan", "Dollar", "Euro", "Yen"],
        "jawaban_index": 4
    },
    {
        "pertanyaan": "7. Gunung tertinggi di dunia adalah?",
        "pilihan": ["Kilimanjaro", "Fuji", "Elbrus", "Everest", "Aconcagua"],
        "jawaban_index": 3
    },
    {
        "pertanyaan": "8. Negara dengan penduduk terbanyak adalah?",
        "pilihan": ["India", "Amerika", "Rusia", "Cina", "Indonesia"],
        "jawaban_index": 3
    },
    {
        "pertanyaan": "9. Siapakah penemu lampu?",
        "pilihan": ["Albert Einstein", "Isaac Newton", "Galileo", "Nikola Tesla", "Thomas Edison"],
        "jawaban_index": 4
    },
    {
        "pertanyaan": "10. Contoh energi terbarukan adalah?",
        "pilihan": ["Batu bara", "Minyak bumi", "Angin", "Gas alam", "Uranium"],
        "jawaban_index": 2
    },
    {
        "pertanyaan": "11. Hewan pemakan tumbuhan disebut?",
        "pilihan": ["Omnivora", "Karnivora", "Herbivora", "Insektivora", "Detritivora"],
        "jawaban_index": 2
    },
    {
        "pertanyaan": "12. Bentuk bumi adalah?",
        "pilihan": ["Segitiga", "Kotak", "Oval", "Bulat", "Kubus"],
        "jawaban_index": 3
    },
    {
        "pertanyaan": "13. Manusia bernapas menggunakan?",
        "pilihan": ["Kulit", "Insang", "Paru-paru", "Trakea", "Rongga hidung"],
        "jawaban_index": 2
    },
    {
        "pertanyaan": "14. Satelit alami bumi adalah?",
        "pilihan": ["Mars", "Bulan", "Matahari", "Venus", "Jupiter"],
        "jawaban_index": 1
    },
    {
        "pertanyaan": "15. Warna primer berikut adalah?",
        "pilihan": ["Merah", "Coklat", "Hitam", "Abu-abu", "Pink"],
        "jawaban_index": 0
    },
    {
        "pertanyaan": "16. Organ yang memompa darah adalah?",
        "pilihan": ["Lambung", "Ginjal", "Paru-paru", "Jantung", "Usus"],
        "jawaban_index": 3
    },
    {
        "pertanyaan": "17. Kerajaan Hindu-Buddha terbesar di Indonesia adalah?",
        "pilihan": ["Sriwijaya", "Majapahit", "Tarumanegara", "Kutai", "Singasari"],
        "jawaban_index": 1
    },
    {
        "pertanyaan": "18. Ibukota provinsi Jawa Timur adalah?",
        "pilihan": ["Bandung", "Medan", "Surabaya", "Semarang", "Denpasar"],
        "jawaban_index": 2
    },
    {
        "pertanyaan": "19. 10 × 10 = ?",
        "pilihan": ["50", "100", "150", "200", "250"],
        "jawaban_index": 1
    },
    {
        "pertanyaan": "20. Alat untuk mengukur suhu adalah?",
        "pilihan": ["Speedometer", "Altimeter", "Voltmeter", "Termometer", "Barometer"],
        "jawaban_index": 3
    }
]

DEFAULT_SKOR = []  # list of {timestamp, skor, benar, total}

# Muat data (membuat file jika belum ada)
soal_data: List[Dict[str, Any]] = load_json_file(SOAL_FILE, DEFAULT_SOAL)
skor_data: List[Dict[str, Any]] = load_json_file(SKOR_FILE, DEFAULT_SKOR)

# ---------------------------
# Fungsi utama aplikasi
# ---------------------------
def tampilkan_menu():
    print("\n=== APLIKASI QUIZ SEDERHANA ===")
    print("1. Mulai Quiz")
    print("2. Tambah Soal")
    print("3. Lihat Riwayat Nilai")
    print("4. Lihat Grafik")
    print("5. Keluar")

def mulai_quiz():
    global soal_data, skor_data
    if not soal_data:
        print("Belum ada soal. Silakan tambahkan soal terlebih dahulu.")
        return

    # Salin dan acak
    soal_acak = soal_data.copy()
    random.shuffle(soal_acak)

    total = len(soal_acak)
    benar = 0

    for idx, s in enumerate(soal_acak, start=1):
        print(f"\nSoal {idx}/{total}:")
        print(s["pertanyaan"])
        for i, pilihan in enumerate(s["pilihan"], start=1):
            print(f"  {i}. {pilihan}")

        # Validasi input pengguna
        while True:
            jawaban = input("Masukkan nomor pilihan: ").strip()
            if not jawaban.isdigit():
                print("Masukkan angka sesuai pilihan.")
                continue
            j = int(jawaban) - 1
            if 0 <= j < len(s["pilihan"]):
                break
            else:
                print("Pilihan tidak valid. Coba lagi.")

        if j == s["jawaban_index"]:
            print("Benar! 🎉")
            benar += 1
        else:
            benar_str = s["pilihan"][s["jawaban_index"]]
            print(f"Salah. Jawaban benar: {benar_str}")

    skor = round(100 * benar / total, 2)
    print("\n--- Hasil Quiz ---")
    print(f"Benar: {benar} / {total}")
    print(f"Nilai: {skor} / 100")

    # Simpan riwayat
    entry = {
        "timestamp": datetime.now().isoformat(timespec='seconds'),
        "skor": skor,
        "benar": benar,
        "total": total
    }
    skor_data.append(entry)
    save_json_file(SKOR_FILE, skor_data)
    print("Riwayat disimpan.")

def tambah_soal():
    global soal_data
    print("\n=== Tambah Soal Baru ===")
    pertanyaan = input("Masukkan pertanyaan: ").strip()
    if not pertanyaan:
        print("Pertanyaan tidak boleh kosong.")
        return

    pilihan = []
    print("Masukkan pilihan jawaban (min 2). Ketik kosong untuk selesai.")
    while True:
        p = input(f"Pilihan {len(pilihan)+1}: ").strip()
        if p == "":
            if len(pilihan) >= 2:
                break
            else:
                print("Harus ada minimal 2 pilihan.")
                continue
        pilihan.append(p)

    # Tampilkan pilihan untuk memilih index jawaban benar
    for i, pl in enumerate(pilihan, start=1):
        print(f"{i}. {pl}")
    while True:
        benar_in = input("Masukkan nomor jawaban benar: ").strip()
        if not benar_in.isdigit():
            print("Masukkan angka.")
            continue
        idx = int(benar_in) - 1
        if 0 <= idx < len(pilihan):
            break
        else:
            print("Nomor tidak valid.")

    # Simpan soal baru
    soal_baru = {
        "pertanyaan": pertanyaan,
        "pilihan": pilihan,
        "jawaban_index": idx
    }
    soal_data.append(soal_baru)
    save_json_file(SOAL_FILE, soal_data)
    print("Soal berhasil ditambahkan dan disimpan ke", SOAL_FILE)

def lihat_riwayat():
    global skor_data
    if not skor_data:
        print("Belum ada riwayat skor.")
        return

    print("\n=== Riwayat Nilai ===")
    for i, e in enumerate(skor_data, start=1):
        t = e.get("timestamp", "unknown")
        skor = e.get("skor", 0)
        benar = e.get("benar", 0)
        total = e.get("total", 0)
        print(f"{i}. {t} - Nilai: {skor} | Benar: {benar}/{total}")

def tampilkan_grafik():
    global skor_data
    if not skor_data:
        print("Belum ada data untuk grafik.")
        return

    # 1) Grafik perkembangan skor per sesi (bar atau line)
    timestamps = [e["timestamp"] for e in skor_data]
    skor_list = [e["skor"] for e in skor_data]
    benar_list = [e["benar"] for e in skor_data]
    total_list = [e["total"] for e in skor_data]

    # Convert timestamps ke label pendek
    labels = [t.replace("T", " ") for t in timestamps]

    # Grafik 1: perkembangan skor (line)
    plt.figure(figsize=(8, 4))
    plt.plot(labels, skor_list, marker='o')  # jangan set warna agar sesuai aturan
    plt.title("Perkembangan Nilai per Sesi")
    plt.xlabel("Waktu")
    plt.ylabel("Nilai (/100)")
    plt.xticks(rotation=45, ha='right')
    plt.tight_layout()
    plt.show()

    # Grafik 2: batang untuk jumlah benar per sesi
    plt.figure(figsize=(8, 4))
    plt.bar(labels, benar_list)
    plt.title("Jumlah Soal Benar per Sesi")
    plt.xlabel("Waktu")
    plt.ylabel("Benar (jumlah)")
    plt.xticks(rotation=45, ha='right')
    plt.tight_layout()
    plt.show()

    # Grafik 3: pie dari total benar vs total salah (akumulatif)
    total_benar = sum(benar_list)
    total_soal = sum(total_list)
    total_salah = total_soal - total_benar
    plt.figure(figsize=(6, 6))
    plt.pie([total_benar, total_salah], labels=["Benar", "Salah"], autopct='%1.1f%%')
    plt.title("Perbandingan Benar vs Salah (Akkumulatif)")
    plt.tight_layout()
    plt.show()

# ---------------------------
# Loop program
# ---------------------------
def main_loop():
    while True:
        tampilkan_menu()
        pilihan = input("Pilih menu (1-5): ").strip()
        if pilihan == "1":
            mulai_quiz()
        elif pilihan == "2":
            tambah_soal()
        elif pilihan == "3":
            lihat_riwayat()
        elif pilihan == "4":
            tampilkan_grafik()
        elif pilihan == "5":
            print("Terima kasih. Sampai jumpa!")
            break
        else:
            print("Pilihan tidak dikenali. Masukkan angka 1-5.")

if __name__ == "__main__":
    main_loop()